site_name: DataLad Workshop @ UKE
site_author: Adina Wagner
repo_url: https://github.com/adswa/dl-workshop
site_url: https://adswa.github.io/dl-workshop/
repo_name: adswa/dl-workshop
docs_dir: docs
copyright: 'Copyright &copy 2022 Adina Wagner'
nav:
  - DataLad Workshop: index.md
  - Preperations for participants: content/getting_started.md
  - Content:
      - Schedule: content/welcome.md
  - Frequently Asked Questions: FAQ.md
  - Contributing: contributing.md
  - Code of Conduct: coc.md
markdown_extensions:
    - admonition
    - codehilite:
        linenums: true
        guess_lang: false
    - pymdownx.arithmatex
    - pymdownx.betterem:
        smart_enable: all
    - pymdownx.caret
    - pymdownx.critic
    - pymdownx.details
    - pymdownx.emoji
    - pymdownx.inlinehilite
    - pymdownx.magiclink
    - pymdownx.mark
    - pymdownx.smartsymbols
    - pymdownx.superfences
    - pymdownx.tasklist:
        custom_checkbox: true
    - pymdownx.tilde
    - toc:
        baselevel: 2
        permalink: true
        separator: "_"
        toc_depth: 3
        anchorlink: false
theme:
    name: material
    language: en
    palette:
        primary: 'black'
        accent: 'yellow'
plugins:
    - search
